language: generic
os:
  - linux
env:
  global:
    # Doctr deploy key for moorepants/resonance
    - secure: "XfldxLY6lCsaJrGBlh3HgDq8MPcaAh9IA8fehK7OhSc2ZqdjvR6cpKvqiue/oFMZwbXDoiFMqJM92oVLsxFcrdPkFytr17nfUE95EX5aKAihz2n5DfbPpN+FwqchDebAsPSVlD/bjDvqZTGcev03+QvaxHRHYLGwHGCZzG4ZcLzxha+QeuQnItolNVhq2cUitRdp+STUF2kkOMGL2ncuiTmuhlQeuA4Ihk03zdKO6+9npd0job27qpSsQgOxbjwdCS4gVqJsJ6ylkceiHzgx/K0H6xUZUTjnq1v75hi1LHhSuO6YQb9vmilmY1tj71J5i/5RD/YvkUTfNlLnLO/sdI6DGvFaynbxpwvDY6jqUOjJ25FgmxRROZg0nXwl4ZMjyNqiCwMYMrTT1qB7Bq6s8t13zJVvJ7vWsYr3BuviLHtaYn88PtCDHG8JclqSNL3UtGRmrVaQxwofXO+zHxck2Av3+UocG8plyiJ0sUJL4D02TMsHwWL7sE5n7Y4pBh1KYn/+mbx9Fg9E/kBcGxif+rUHvEUg/Gk9V8GHe4ksCga8Xjr/nXghoc5v5rWaKoQwDyLk6dAOxYRNvKrZl+pCDhiOHMJTJoiX8HFaAd32Q6/1CwUNuaBX2n5XZIpgwOHj9Fl9Fzi/HhONxY7jCzzugoWNmqRYrLR2Tr/mNnlijhU="
  matrix:
    - DEP_VERSIONS="oldest"  # Approximately the versions available in the last LTS release of Ubuntu.
    - DEP_VERSIONS="latest"
install:
  - |
    MINICONDA_URL="https://repo.continuum.io/miniconda"
    MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
    curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
    bash $MINICONDA_FILE -b
  - source ~/miniconda3/bin/activate root
  - conda config --set always_yes yes
  - conda update -q conda
  - if [[ $DEP_VERSIONS == "oldest" ]]; then
      conda env create -f dev-oldest-environment.yml;
      source activate resonance-dev-oldest;
    elif [[ $DEP_VERSIONS == "latest" ]]; then
      conda env create -f dev-environment.yml;
      source activate resonance-dev;
    fi
  - python setup.py install
before_script:
  - conda info
  - conda list
  - export MPLBACKEND=Agg
script:
  - set -e
  # run tests on resonance lib
  - py.test --cov=resonance
  # only build notebooks with latest versions of software
  - |
    if [[ $DEP_VERSIONS == "latest" ]]; then
      # execute notebooks, convert to html
      bin/execute_notebooks.sh;
      # set up an area for deployed html/ipynb files and push to gh_pages
      bin/prepare_deploy.sh;
      git reset --hard;
      git clean -Xdf notebooks/;
      git clean -xdf notebooks/;
      pip install doctr;
      doctr deploy --built-docs=deploy/ .;
    fi
  # try building the documentation
  - cd docs
  - make html

notifications:
    email: false
