language: generic
os:
  - linux
install:
  - |
    MINICONDA_URL="https://repo.continuum.io/miniconda"
    MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
    curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
    bash $MINICONDA_FILE -b
  - source ~/miniconda3/bin/activate root
  - conda config --set always_yes yes
  - conda update -q conda
  - conda env create -f dev-environment.yml
  - source activate resonance-dev
  - pip install .
before_script:
  - conda info
  - conda list
script:
  - bash bin/build_notebooks.sh
  - bash bin/execute_notebooks.sh
  - py.test resonance/
notifications:
    email: false
