name: resonance-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.5
  - setuptools
  - pip
  - pytest
  - pytest-cov
  - coverage
  - sphinx
  - numpy
  - scipy
  - matplotlib >=2.1
  - pandas
  - sympy
  - notebook
  - ipywidgets
  - nbconvert
  - jupyter_contrib_nbextensions
