name: resonance-dev-oldest
channels:
  - conda-forge
  - defaults
dependencies:
  - python =3.6.*
  - setuptools
  - pip
  - pytest
  - pytest-cov
  - coverage
  - sphinx
  - numpy =1.13.*
  - scipy =0.19.*
  - matplotlib =2.1.*
  - pandas =0.17.*
  - sympy =1.1.*
  - notebook =5.2.*
  - ipywidgets
  - nbconvert
  - jupyter_contrib_nbextensions
