name: resonance-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.5
  - setuptools >=20.7
  - pip >=8.1
  - pytest
  - pytest-cov
  - coverage
  - sphinx
  - numpy >=1.11
  - scipy >=0.17
  - matplotlib >=2.1
  - pandas >=0.17
  - sympy >=0.7.6
  - notebook
  - ipywidgets
  - nbconvert
  - jupyter_contrib_nbextensions
