name: resonance-dev-oldest
channels:
  - conda-forge
  - defaults
dependencies:
  - python =3.6.*
  - setuptools
  - pip
  - pytest
  - pytest-cov
  - coverage
  - sphinx
  - jupyter_sphinx
  - numpy =1.14.*  # Ubuntu 18.04 is 1.13
  - scipy =1.0.*  # Ubuntu 18.04 is 0.19
  - matplotlib =2.1.*
  - pandas =0.20.*  # Ubuntu 18.04 is 0.17
  - sympy =1.1.*
