name: resonance-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.5
  - setuptools
  - pip
  - pytest
  - ipywidgets
  - nbconvert
  - notebook<5.1
  - numpy
  - matplotlib
  - scipy
  - pandas
  - sympy
  - pip:
    - https://github.com/moorepants/rst-to-ipynb/archive/pycon-funcs.zip
